[package]
name = "hiway-loom"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hiway = { version = "=0.1.0", path = "../hiway", default-features = false, features = ["std"] }

[dev-dependencies]
loom = { version = "0.7", features = ["futures"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
